### ISSUE TITLE
Hi, I have a question.

### ISSUE THREAD

**Issue by DoCKeK** [Xin1337/Guessing-Game-Assembly#1]
Hi, can you help me with this? I found you on github in the warchill crack theme. I run start.cmd and only this comes out
![image](https://github.com/user-attachments/assets/cc4fdcd6-606f-4a27-b157-a04caa544f59)
Sorry that's off topic, I just don't know how to contact you

**Comment by Xin1337** [comment]
Hi, I think you need to update the offsets to make it work I haven't touched that source for quite some time now.
You can message me on discord: differed
